### ISSUE TITLE
tests not passing

### ISSUE THREAD

**Issue by mcollina** [nodejs/http2#10]
```
=== release test-async-wrap-check-providers ===
Path: parallel/test-async-wrap-check-providers
Not all keys have been used:
[ 'HTTP2SESSION', 'HTTP2STREAM' ]

assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: 2 === 0
    at process.<anonymous> (/Users/matteo/Repositories/http2/test/parallel/test-async-wrap-check-providers.js:122:12)
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
Command: out/Release/node /Users/matteo/Repositories/http2/test/parallel/test-async-wrap-check-providers.js
=== release test-process-versions ===
Path: parallel/test-process-versions
assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: [ 'ares',
  'cldr',
  'http_parser',
  'icu',
  'modules',
  'nghttp2',
  'node',
  'openssl',
  'tz',
  'unicode',
  'uv',
  'v deepStrictEqual [ 'ares',
  'cldr',
  'http_parser',
  'icu',
  'modules',
  'node',
  'openssl',
  'tz',
  'unicode',
  'uv',
  'v8',
  'zlib'
    at Object.<anonymous> (/Users/matteo/Repositories/http2/test/parallel/test-process-versions.js:22:8)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
Command: out/Release/node /Users/matteo/Repositories/http2/test/parallel/test-process-versions.js
[02:00|% 100|+ 1276|-   2]: Done
make: *** [test] Error 1
```

**Comment by jasnell** [comment]
+1, I'll fix this in the next round of updates

**Comment by mcollina** [comment]
Fixed.
