### ISSUE TITLE
http2: failures on raspbian

### ISSUE THREAD

**Issue by jasnell** [nodejs/http2#105]
https://ci.nodejs.org/job/node-test-binary-arm/7999/RUN_SUBSET=4,label=pi2-raspbian-wheezy/console

```
not ok 93 parallel/test-http2-create-client-connect
  ---
  duration_ms: 1.537
  severity: fail
  stack: |-
    (node:11017) ExperimentalWarning: The http2 module is an experimental API.
    internal/http2/core.js:375
        handle.consume(socket._handle._externalStream);
                                     ^
    
    TypeError: Cannot read property '_externalStream' of null
        at internal/http2/core.js:375:34
        at new Http2Session (internal/http2/core.js:435:7)
        at createClientSession (internal/http2/core.js:1340:19)
        at connect (internal/http2/core.js:1402:19)
        at items.forEach (/home/iojs/build/workspace/node-test-binary-arm/test/parallel/test-http2-create-client-connect.js:39:20)
        at Array.forEach (native)
        at Http2Server.<anonymous> (/home/iojs/build/workspace/node-test-binary-arm/test/parallel/test-http2-create-client-connect.js:37:11)
        at Http2Server.<anonymous> (/home/iojs/build/workspace/node-test-binary-arm/test/common.js:462:15)
        at emitNone (events.js:105:13)
        at Http2Server.emit (events.js:207:7)
  ...
not ok 94 parallel/test-http2-server-startup
  ---
  duration_ms: 3.639
  severity: fail
  stack: |-
    (node:11033) ExperimentalWarning: The http2 module is an experimental API.
    
    assert.js:86
      throw new assert.AssertionError({
      ^
    AssertionError: server timeout failed
        at Timeout.setTimeout [as _onTimeout] (/home/iojs/build/workspace/node-test-binary-arm/test/parallel/test-http2-server-startup.js:80:35)
        at ontimeout (timers.js:407:14)
        at tryOnTimeout (timers.js:271:5)
        at Timer.listOnTimeout (timers.js:235:5)
  ...
```

**Comment by jasnell** [comment]
This should be fixed!
