### ISSUE TITLE
Sending illegal frame (DATA) in CLOSED state. and AssertionError: false == true

### ISSUE THREAD

**Issue by dinfyru** [nodejs/http2#30]
node -v 6.9.2
One error
```
Debug: internal, implementation, error
	Error: Sending illegal frame (DATA) in CLOSED state.
	at Stream.transition [as _transition] (/var/www/revizor-game.ru/node_modules/http2/lib/protocol/stream.js:628:33)
	at Stream._finishing (/var/www/revizor-game.ru/node_modules/http2/lib/protocol/stream.js:349:10)
	at emitNone (events.js:67:13)
	at Stream.emit (events.js:166:7)
	at finishMaybe (_stream_writable.js:468:14)
	at endWritable (_stream_writable.js:478:3)
	at Stream.Writable.end (_stream_writable.js:443:5)
	at OutgoingResponse._finish (/var/www/revizor-game.ru/node_modules/http2/lib/http.js:352:17)
	at emitNone (events.js:72:20)
	at OutgoingResponse.emit (events.js:166:7)
	at finishMaybe (_stream_writable.js:468:14)
	at endWritable (_stream_writable.js:478:3)
	at OutgoingResponse.Writable.end (_stream_writable.js:443:5)
	at OutgoingResponse.end (/var/www/revizor-game.ru/node_modules/http2/lib/http.js:753:40)
	at ReadStream.onend (_stream_readable.js:490:10)
	at ReadStream.g (events.js:260:16)
```
second
```
Debug: internal, implementation, error
    AssertionError: false == true
    at Connection._send (/var/www/revizor-game.ru/node_modules/http2/lib/protocol/connection.js:326:9)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```
My server.js
```
$lib.s = new Hapi.Server();
var listener = http2.createServer({
    key: fs.readFileSync('/var/www/revizor-game.ru.key', 'utf8'),
    cert: fs.readFileSync('/var/www/ca.crt', 'utf8'),
    pfx: fs.readFileSync('/var/www/pfx.pfx')
});

$lib.s.connection({
    listener: listener,
    host: 'revizor-game.ru',
    port: 443,
    tls: true
    // tls: {
    //     key: fs.readFileSync('/var/www/revizor-game.ru.key', 'utf8'),
    //     cert: fs.readFileSync('/var/www/ca.crt', 'utf8')
    // }
});
```
and boot.js (clustering) - http://pastebin.com/YzGsJVUk

**Comment by mcollina** [comment]
This is definitely not the module you are looking for. That is https://github.com/molnarg/node-http2.

This is an implementation in Node core of http2, which will be shipped in the next major release (hopefully).

**Comment by dinfyru** [comment]
@mcollina Sry, my bad))) But mb you can help me some, plz)
