### ISSUE TITLE
REPL does not have 'http2' as a built-in library.

### ISSUE THREAD

**Issue by yosuke-furukawa** [nodejs/http2#82]
REPL has 'http' and 'https' as built-in libraries.
But 'http2' is not included.

* **Subsystem**:
http2

**Comment by sebdeckers** [comment]
Seems to work for me. Are you running the correct binary?

## v8.0.0-pre

```
$ ./node
> Object.keys(require('http2'))
[ 'constants',
  'getDefaultSettings',
  'getPackedSettings',
  'createServer',
  'createSecureServer',
  'createServerSession',
  'connect',
  'secureConnect' ]
```

## v7.10.0

```
$ node
> Object.keys(require('http2'))
Error: Cannot find module 'http2'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at repl:1:13
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:339:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:536:10)
```

**Comment by addaleax** [comment]
Seems like this can be closed now :)
